### ISSUE TITLE
两处bug

### ISSUE THREAD

**Issue by MacwinWin** [xugongli/PyQt5-BaiduMapCrawler#3]
1. `$ python run.py`
`Traceback (most recent call last):`
`  File "run.py", line 12, in <module> from Mainwindow.Mainwindow import Ui_MainWindow
  File "C:\Users\Administrator\iCloudDrive\Documents\development\GitHub\PyQt5-BaiduMapCrawler-master\Mainwindow\Mainwindow.py", line 251, in <module> from qtpandas.views.DataTableView import DataTableWidget`
`  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\qtpandas\views\DataTableView.py", line 13, in <module> from qtpandas.views.EditDialogs import AddAttributesDialog, RemoveAttributesDialog`
`  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\qtpandas\views\EditDialogs.py", line 17, in <module> from pandas.tslib import NaTType`
`ModuleNotFoundError: No module named 'pandas.tslib'
`
解决方法：
文件中相应位置改为：`from pandas._libs.tslibs.nattype import NaTType`
2. `$ python run.py`
`Traceback (most recent call last):`
`  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\qtpandas\views\DataTableView.py", line 70, in mouseMoveEvent`
`    self.startDrag(self.indexAt(event.pos()))`
`  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\qtpandas\views\DataTableView.py", line 66, in startDrag`
`    result = drag.start(Qt.MoveAction)`
`AttributeError: 'QDrag' object has no attribute 'start'
`
解决方法：
文件中相应位置将‘drag.start’改为‘drag.exec_’

**Comment by xugongli** [comment]
谢谢反馈，这是由于pandas和pyqt5版本的原因导致的。暂时没有好的方法。
只能使用指定版本的pandas和pyqt5才可以正常运行。
