### ISSUE TITLE
运行时提示出错

### ISSUE THREAD

**Issue by shenyaocan** [xugongli/PyQt5-BaiduMapCrawler#9]
运行时提示出错，不知道怎么处理，希望版主能指点指点。谢谢

Traceback (most recent call last):
  File "run.py", line 12, in <module>
    from Mainwindow.Mainwindow import Ui_MainWindow
  File "C:\Users\sheny\PycharmProjects\untitled7\PyQt5-BaiduMapCrawler-master\Mainwindow\Mainwindow.py", line 251, in <module>
    from qtpandas.views.DataTableView import DataTableWidget
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtpandas-1.0.4-py3.7.egg\qtpandas\__init__.py", line 20, in <module>
    from qtpandas.views.EditDialogs import (AddAttributesDialog,
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtpandas-1.0.4-py3.7.egg\qtpandas\views\EditDialogs.py", line 17, in <module>
    from pandas.tslib import NaTType
ModuleNotFoundError: No module named 'pandas.tslib'

**Comment by xugongli** [comment]
不好意思，刚刚看到，pandas版本太高了，可以安装pandas的0.23版本试试，应该可以解决问题。
还有这个小程序就是一个玩具，拿来学习下pyqt5就行，不适合抓取大量数据。
